[
  "Pašilaičių g. 10, Vilnius, Lithuania",
  "Antakalnio g. 74, Vilnius, Lithuania",
  "Gerosios Vilties g. 28, Vilnius, Lithuania",
  "Žirmūnų g. 32, Vilnius, Lithuania",
  "Žemaitės g. 3, Vilnius, Lithuania",
  "Taikos g. 187, Vilnius, Lithuania",
  "Beržyno g. 7A, Vilnius, Lithuania",
  "Paberžės g. 20, Vilnius, Lithuania",
  "Latvių g. 40, Vilnius, Lithuania",
  "A. Kojelavičiaus g. 298, Vilnius, Lithuania",
  "Dariaus ir Girėno g. 14, Vilnius, Lithuania",
  "Vido Maciulevičiaus g. 32, Vilnius, Lithuania",
  "K. Donelaičio g. 12, Vilnius, Lithuania",
  "Rinktinės g. 28A, Vilnius, Lithuania",
  "Pelesos g. 15, Vilnius, Lithuania",
  "Miglos g. 3, Vilnius, Lithuania",
  "Gabijos g. 1, Vilnius, Lithuania",
  "Fabijoniškių g. 7, Vilnius, Lithuania",
  "Gelvonų g. 1, Vilnius, Lithuania",
  "Gėlių g. 9A, Vilnius, Lithuania",
  "Muitinės g. 30, Vilnius, Lithuania",
  "Dzūkų g. 32, Vilnius, Lithuania",
  "Minties g. 1, Vilnius, Lithuania",
  "Vydūno g. 11A, Vilnius, Lithuania",
  "Didlaukio g. 35, Vilnius, Lithuania",
  "Erfurto g. 42, Vilnius, Lithuania",
  "Justiniškių g. 65, Vilnius, Lithuania",
  "Trakų g. 12, Vilnius, Lithuania",
  "S. Stanevičiaus g. 21, Vilnius, Lithuania",
  "Justiniškių g. 47, Vilnius, Lithuania",
  "Taikos g. 99, Vilnius, Lithuania",
  "Gedvydžių g. 25, Vilnius, Lithuania",
  "Antakalnio g. 108, Vilnius, Lithuania",
  "Laisvės pr. 59, Vilnius, Lithuania",
  "Lydos g. 5, Vilnius, Lithuania",
  "Suvalkų g. 6, Vilnius, Lithuania",
  "Birželio 23-iosios g. 6A, Vilnius, Lithuania",
  "Lakštingalų g. 10, Vilnius, Lithuania",
  "Dzūkų g. 29, Vilnius, Lithuania",
  "Lazdynų g. 36, Vilnius, Lithuania",
  "Kapsų g. 7, Vilnius, Lithuania",
  "Kovo 11-osios g. 54, Vilnius, Lithuania",
  "Popieriaus g. 7, Vilnius, Lithuania",
  "A. Vivulskio g. 8A, Vilnius, Lithuania",
  "Algimanto Petro Kavoliuko g. 5, Vilnius, Lithuania",
  "Keramikų g. 34, Vilnius, Lithuania",
  "Smėlio g. 13, Vilnius, Lithuania",
  "Taikos g. 190, Vilnius, Lithuania",
  "Architektų g. 204, Vilnius, Lithuania",
  "Gelvonų g. 24, Vilnius, Lithuania",
  "Brolių g. 18, Vilnius, Lithuania",
  "Mindaugo g. 15A, Vilnius, Lithuania",
  "Architektų g. 44, Vilnius, Lithuania",
  "Juodšilių g. 10, Vilnius, Lithuania",
  "Čiobiškio g. 17, Vilnius, Lithuania",
  "Žirmūnų g. 110, Vilnius, Lithuania",
  "Taikos g. 30, Vilnius, Lithuania",
  "Darželio g. 7, Vilnius, Lithuania",
  "Musninkų g. 10, Vilnius, Lithuania",
  "Lentvario g. 1A, Vilnius, Lithuania",
  "Justiniškių g. 84, Vilnius, Lithuania",
  "I. Kanto al. 7A, Vilnius, Lithuania",
  "Krokuvos g. 6A, Vilnius, Lithuania",
  "Loretos Asanavičiūtės g. 7, Vilnius, Lithuania",
  "Kalvarijų g. 186, Vilnius, Lithuania",
  "Tujų g. 1, Vilnius, Lithuania",
  "Bistryčios g. 3, Vilnius, Lithuania",
  "Miglos g. 53, Vilnius, Lithuania",
  "Algimanto Petro Kavoliuko g. 12, Vilnius, Lithuania",
  "Žirmūnų g. 10, Vilnius, Lithuania",
  "M. Daukšos g. 15, Vilnius, Lithuania",
  "Erfurto g. 21, Vilnius, Lithuania",
  "Kovo 11-osios g. 29A, Vilnius, Lithuania",
  "Žirmūnų g. 50, Vilnius, Lithuania",
  "Architektų g. 162, Vilnius, Lithuania",
  "Z. Sierakausko g. 28, Vilnius, Lithuania",
  "S. Stanevičiaus g. 86, Vilnius, Lithuania",
  "J. Jasinskio g. 17, Vilnius, Lithuania",
  "Taikos g. 31, Vilnius, Lithuania",
  "Genių g. 12, Vilnius, Lithuania",
  "Didlaukio g. 66, Vilnius, Lithuania",
  "Sietyno g. 5, Vilnius, Lithuania",
  "Skroblų g. 13, Vilnius, Lithuania",
  "Minties g. 40, Vilnius, Lithuania",
  "Vytenio g. 41, Vilnius, Lithuania",
  "Žirmūnų g. 108, Vilnius, Lithuania",
  "Architektų g. 16, Vilnius, Lithuania",
  "Igno Šimulionio g. 14, Vilnius, Lithuania",
  "Dūkštų g. 14, Vilnius, Lithuania",
  "Žalgirio g. 115, Vilnius, Lithuania",
  "Povilo Višinskio g. 23, Vilnius, Lithuania",
  "Eduardo Andrė g. 6, Vilnius, Lithuania",
  "Filaretų g. 19, Vilnius, Lithuania",
  "Rinktinės g. 5B, Vilnius, Lithuania",
  "P. Žadeikos g. 14A, Vilnius, Lithuania",
  "Ukmergės g. 204, Vilnius, Lithuania",
  "Gabijos g. 21, Vilnius, Lithuania",
  "S. Stanevičiaus g. 68, Vilnius, Lithuania",
  "Gardino g. 8, Vilnius, Lithuania",
  "Žirmūnų g. 89, Vilnius, Lithuania",
  "Pergalės g. 20, Vilnius, Lithuania",
  "Gerosios Vilties g. 7A, Vilnius, Lithuania",
  "Jūratės g. 4A, Vilnius, Lithuania",
  "Šaltkalvių g. 30, Vilnius, Lithuania",
  "Architektų g. 108, Vilnius, Lithuania",
  "Žemynos g. 13, Vilnius, Lithuania",
  "Laisvės pr. 46, Vilnius, Lithuania",
  "Architektų g. 62, Vilnius, Lithuania",
  "Žemynos g. 41, Vilnius, Lithuania",
  "Taikos g. 130, Vilnius, Lithuania",
  "Viršuliškių g. 9, Vilnius, Lithuania",
  "J. Kolaso g. 15, Vilnius, Lithuania",
  "Žirmūnų g. 13, Vilnius, Lithuania",
  "Verkių g. 17, Vilnius, Lithuania",
  "Žolyno g. 45A, Vilnius, Lithuania",
  "Žolyno g. 44, Vilnius, Lithuania",
  "Parko g. 8A, Vilnius, Lithuania",
  "Rinktinės g. 38A, Vilnius, Lithuania",
  "Justiniškių g. 45, Vilnius, Lithuania",
]